structure(list(url = "http://www.camara.leg.br/SitCamaraWS/Proposicoes.asmx/ListarProposicoesVotadasEmPlenario?tipo=PL&ano=2008&numero=1247", 
    status_code = 200L, headers = structure(list(date = "Sun, 02 Dec 2018 12:17:14 GMT", 
        server = "nginx/1.8.1", `content-type` = "text/xml; charset=utf-8", 
        `cache-control` = "private, max-age=0", `x-aspnet-version` = "4.0.30319", 
        `x-powered-by` = "ASP.NET", `x-varnish` = "641380576", 
        age = "0", via = "1.1 varnish", `x-cache-action` = "MISS", 
        `set-cookie` = "REDACTED", vary = "User-Agent", `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sun, 02 Dec 2018 12:17:14 GMT", 
            server = "nginx/1.8.1", `content-type` = "text/xml; charset=utf-8", 
            `cache-control` = "private, max-age=0", `x-aspnet-version` = "4.0.30319", 
            `x-powered-by` = "ASP.NET", `x-varnish` = "641380576", 
            age = "0", via = "1.1 varnish", `x-cache-action` = "MISS", 
            `set-cookie` = "REDACTED", vary = "User-Agent", `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = "www.camara.leg.br", 
        flag = FALSE, path = "/", secure = FALSE, expiration = structure(Inf, class = c("POSIXct", 
        "POSIXt")), name = "BALANCEID", value = "REDACTED"), row.names = c(NA, 
    -1L), class = "data.frame"), content = charToRaw("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<proposicoes>\r\n  <proposicao>\r\n    <codProposicao>350108</codProposicao>\r\n    <nomeProposicao>PL 940/2007</nomeProposicao>\r\n    <dataVotacao>18/11/2008</dataVotacao>\r\n  </proposicao>\r\n  <proposicao>\r\n    <codProposicao>366816</codProposicao>\r\n    <nomeProposicao>PL 1990/2007</nomeProposicao>\r\n    <dataVotacao>11/03/2008</dataVotacao>\r\n  </proposicao>\r\n  <proposicao>\r\n    <codProposicao>377706</codProposicao>\r\n    <nomeProposicao>PL 2468/2007</nomeProposicao>\r\n    <dataVotacao>27/05/2008</dataVotacao>\r\n  </proposicao>\r\n  <proposicao>\r\n    <codProposicao>396209</codProposicao>\r\n    <nomeProposicao>PL 3452/2008</nomeProposicao>\r\n    <dataVotacao>12/08/2008</dataVotacao>\r\n  </proposicao>\r\n  <proposicao>\r\n    <codProposicao>403395</codProposicao>\r\n    <nomeProposicao>PL 3674/2008</nomeProposicao>\r\n    <dataVotacao>29/10/2008</dataVotacao>\r\n  </proposicao>\r\n  <proposicao>\r\n    <codProposicao>403395</codProposicao>\r\n    <nomeProposicao>PL 3674/2008</nomeProposicao>\r\n    <dataVotacao>29/10/2008</dataVotacao>\r\n  </proposicao>\r\n  <proposicao>\r\n    <codProposicao>403395</codProposicao>\r\n    <nomeProposicao>PL 3674/2008</nomeProposicao>\r\n    <dataVotacao>29/10/2008</dataVotacao>\r\n  </proposicao>\r\n  <proposicao>\r\n    <codProposicao>403395</codProposicao>\r\n    <nomeProposicao>PL 3674/2008</nomeProposicao>\r\n    <dataVotacao>29/10/2008</dataVotacao>\r\n  </proposicao>\r\n  <proposicao>\r\n    <codProposicao>403395</codProposicao>\r\n    <nomeProposicao>PL 3674/2008</nomeProposicao>\r\n    <dataVotacao>29/10/2008</dataVotacao>\r\n  </proposicao>\r\n  <proposicao>\r\n    <codProposicao>403395</codProposicao>\r\n    <nomeProposicao>PL 3674/2008</nomeProposicao>\r\n    <dataVotacao>04/11/2008</dataVotacao>\r\n  </proposicao>\r\n</proposicoes>"), 
    date = structure(1543753034, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.7e-05, 
    connect = 0.284077, pretransfer = 0.284161, starttransfer = 0.568952, 
    total = 0.57058)), class = "response")
