structure(list(url = "http://legis.senado.leg.br/dadosabertos/dados/ListaVotacoes2013.xml", 
    status_code = 200L, headers = structure(list(date = "Sun, 02 Dec 2018 12:18:27 GMT", 
        `content-type` = "text/xml", `last-modified` = "Mon, 16 Jan 2017 09:01:13 GMT", 
        `accept-ranges` = "bytes", etag = "W/\"587c8bd9-5fbda2\"", 
        `content-encoding` = "gzip", vary = "Accept-Encoding", 
        age = "0", `x-cache` = "MISS", connection = "close", 
        `transfer-encoding` = "chunked"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 200L, version = "HTTP/1.1", 
        headers = structure(list(date = "Sun, 02 Dec 2018 12:18:27 GMT", 
            `content-type` = "text/xml", `last-modified` = "Mon, 16 Jan 2017 09:01:13 GMT", 
            `accept-ranges` = "bytes", etag = "W/\"587c8bd9-5fbda2\"", 
            `content-encoding` = "gzip", vary = "Accept-Encoding", 
            age = "0", `x-cache` = "MISS", connection = "close", 
            `transfer-encoding` = "chunked"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw(NA_character_), date = structure(1543753107, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 0.652418, 
    connect = 1.207356, pretransfer = 1.207461, starttransfer = 1.515478, 
    total = 3.363581)), class = "response")
